// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KnockHostApi {
  func getFcmToken(completion: @escaping (Result<String, Error>) -> Void)
  func getApnsToken(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KnockHostApiSetup {
  /// The codec used by KnockHostApi.
  /// Sets up an instance of `KnockHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KnockHostApi?) {
    let getFcmTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.knock_flutter.KnockHostApi.getFcmToken", binaryMessenger: binaryMessenger)
    if let api = api {
      getFcmTokenChannel.setMessageHandler { _, reply in
        api.getFcmToken() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getFcmTokenChannel.setMessageHandler(nil)
    }
    let getApnsTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.knock_flutter.KnockHostApi.getApnsToken", binaryMessenger: binaryMessenger)
    if let api = api {
      getApnsTokenChannel.setMessageHandler { _, reply in
        api.getApnsToken() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getApnsTokenChannel.setMessageHandler(nil)
    }
  }
}
